# Change these first
owner: mthorin # Your GitHub organization or username, where this repository lives
repo: jwt-pizza-upptime # The name of this repository

sites:
  - name: JWT Pizza
    url: https://pizza.tictactoevs.click
  - name: JWT Pizza Backend
    url: https://pizza-service.tictactoevs.click

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: pizza-status.tictactoevs.click
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: JWT Pizza Status
  introTitle: "**JWT Pizza Status** provided by Upptime."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/mthorin/jwt-pizza-upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
